-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v12 by cesarhernanruscica@gmail.com *
-- ************************************** "temporadas"
CREATE TABLE temporadas
(
 id          int NOT NULL AUTO_INCREMENT,
 nombre      varchar(100) NOT NULL ,
 descripcion varchar(100) NOT NULL ,
 apertura    varchar(100) NOT NULL ,
 cierre      varchar(100) NOT NULL ,
 CONSTRAINT PK_6 PRIMARY KEY CLUSTERED (id ASC)
);
-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [actores]
CREATE TABLE actores
(
 id                  int NOT NULL AUTO_INCREMENT,
 nombre              varchar(100) NOT NULL ,
 descripcion         text NOT NULL ,
 captura_enlace      varchar(50) NOT NULL ,
 fecha_nacimiento    datetime NOT NULL ,
 fecha_fallecimiento datetime NOT NULL ,
 CONSTRAINT PK_38 PRIMARY KEY CLUSTERED (id ASC)
);
-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** sketches_tipos
CREATE TABLE sketches_tipos
(
 id             int NOT NULL AUTO_INCREMENT,
 nombre         varchar(100) NOT NULL ,
 descripcion    text NOT NULL ,
 captura_enlace varchar(50) NOT NULL ,
 CONSTRAINT PK_38 PRIMARY KEY CLUSTERED (id ASC)
);
-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [capitulos]
CREATE TABLE capitulos
(
 id                   int NOT NULL AUTO_INCREMENT,
 nombre               varchar(100) NOT NULL ,
 descripcion          varchar(100) NOT NULL ,
 fecha_emision        datetime NOT NULL ,
 transcripcion_enlace varchar(50) NOT NULL ,
 id_temporada         int NOT NULL ,
 CONSTRAINT PK_12 PRIMARY KEY CLUSTERED (id ASC),
 CONSTRAINT FK_33 FOREIGN KEY (id_temporada)  REFERENCES temporadas(id)
);
-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [personajes]
CREATE TABLE personajes
(
 id             int NOT NULL AUTO_INCREMENT,
 nombre         varchar(100) NOT NULL ,
 descripcion    text NOT NULL ,
 captura_enlace varchar(50) NOT NULL ,
 id_sketch_tipo int NOT NULL ,
 CONSTRAINT PK_112 PRIMARY KEY CLUSTERED (id ASC),
 CONSTRAINT FK_153 FOREIGN KEY (id_sketch_tipo)  REFERENCES sketches_tipos(id)
);
-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** sketches_particulares
CREATE TABLE sketches_particulares
(
 id             int NOT NULL AUTO_INCREMENT,
 nombre         varchar(100) NOT NULL ,
 descripcion    text NOT NULL ,
 captura_enlace varchar(50) NOT NULL ,
 indice_tiempos varchar(100) NOT NULL ,
 id_sketch_tipo int NOT NULL ,
 CONSTRAINT PK_38 PRIMARY KEY CLUSTERED (id ASC),
 CONSTRAINT FK_49 FOREIGN KEY (id_sketch_tipo)  REFERENCES sketches_tipos(id)
);
-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** sketches_particulares_x_capitulos
CREATE TABLE sketches_particulares_x_capitulos
(
 id                   int NOT NULL AUTO_INCREMENT,
 id_capitulo          int NOT NULL ,
 id_sketch_particular int NOT NULL ,
 CONSTRAINT PK_53 PRIMARY KEY CLUSTERED (id ASC),
 CONSTRAINT FK_58 FOREIGN KEY (id_capitulo)  REFERENCES capitulos(id),
 CONSTRAINT FK_71 FOREIGN KEY (id_sketch_particular)  REFERENCES sketches_particulares(id)
);
-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** sketches_particulares_x_actores
CREATE TABLE sketches_particulares_x_actores
(
 id                   int NOT NULL AUTO_INCREMENT,
 id_sketch_particular int NOT NULL ,
 id_actor             int NOT NULL ,
 CONSTRAINT PK_91 PRIMARY KEY CLUSTERED (id ASC),
 CONSTRAINT FK_107 FOREIGN KEY (id_actor)  REFERENCES actores(id),
 CONSTRAINT FK_87 FOREIGN KEY (id_sketch_particular)  REFERENCES sketches_particulares(id)
);
-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** actores_x_personajes
CREATE TABLE actores_x_personajes
(
 id           int NOT NULL AUTO_INCREMENT,
 id_actor     int NOT NULL ,
 id_personaje int NOT NULL ,
 CONSTRAINT PK_118 PRIMARY KEY CLUSTERED (id ASC),
 CONSTRAINT FK_119 FOREIGN KEY (id_actor)  REFERENCES actores(id),
 CONSTRAINT FK_150 FOREIGN KEY (id_personaje)  REFERENCES personajes(id)
);


