-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [temporadas]
CREATE TABLE [temporadas]
(
 [id]          int NOT NULL ,
 [nombre]      varchar(100) NOT NULL ,
 [descripcion] varchar(100) NOT NULL ,
 [apertura]    varchar(100) NOT NULL ,
 [cierre]      varchar(100) NOT NULL ,


 CONSTRAINT [PK_6] PRIMARY KEY CLUSTERED ([id] ASC)
);
GO

-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [actores]
CREATE TABLE [actores]
(
 [id]             int NOT NULL ,
 [nombre]         varchar(100) NOT NULL ,
 [descripcion]    text NOT NULL ,
 [captura_enlace] varchar(50) NOT NULL ,


 CONSTRAINT [PK_38] PRIMARY KEY CLUSTERED ([id] ASC)
);
GO

-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [sketch_tipo]
CREATE TABLE [sketch_tipo]
(
 [id]             int NOT NULL ,
 [nombre]         varchar(100) NOT NULL ,
 [descripcion]    text NOT NULL ,
 [captura_enlace] varchar(50) NOT NULL ,


 CONSTRAINT [PK_38] PRIMARY KEY CLUSTERED ([id] ASC)
);
GO

-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [capitulos]
CREATE TABLE [capitulos]
(
 [id]                   int NOT NULL ,
 [nombre]               varchar(100) NOT NULL ,
 [descripcion]          varchar(100) NOT NULL ,
 [fecha_emision]        datetime NOT NULL ,
 [transcripcion_enlace] varchar(50) NOT NULL ,
 [id_temporada]         int NOT NULL ,


 CONSTRAINT [PK_12] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_33] FOREIGN KEY ([id_temporada])  REFERENCES [temporadas]([id])
);
GO


CREATE NONCLUSTERED INDEX [FK_35] ON [capitulos] 
 (
  [id_temporada] ASC
 )

GO

-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [personajes]
CREATE TABLE [personajes]
(
 [id]             int NOT NULL ,
 [nombre]         varchar(100) NOT NULL ,
 [descripcion]    text NOT NULL ,
 [captura_enlace] varchar(50) NOT NULL ,
 [id_sketch_tipo] int NOT NULL ,


 CONSTRAINT [PK_112] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_153] FOREIGN KEY ([id_sketch_tipo])  REFERENCES [sketch_tipo]([id])
);
GO


CREATE NONCLUSTERED INDEX [FK_155] ON [personajes] 
 (
  [id_sketch_tipo] ASC
 )

GO

-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [sketch_particular]
CREATE TABLE [sketch_particular]
(
 [id]             int NOT NULL ,
 [nombre]         varchar(100) NOT NULL ,
 [descripcion]    text NOT NULL ,
 [captura_enlace] varchar(50) NOT NULL ,
 [indice_tiempos] varchar(100) NOT NULL ,
 [id_sketch_tipo] int NOT NULL ,


 CONSTRAINT [PK_38] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_49] FOREIGN KEY ([id_sketch_tipo])  REFERENCES [sketch_tipo]([id])
);
GO


CREATE NONCLUSTERED INDEX [FK_51] ON [sketch_particular] 
 (
  [id_sketch_tipo] ASC
 )

GO

-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [sketchs_particulares_x_capitulos]
CREATE TABLE [sketchs_particulares_x_capitulos]
(
 [id]                   int NOT NULL ,
 [id_capitulo]          int NOT NULL ,
 [id_sketch_particular] int NOT NULL ,


 CONSTRAINT [PK_53] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_58] FOREIGN KEY ([id_capitulo])  REFERENCES [capitulos]([id]),
 CONSTRAINT [FK_71] FOREIGN KEY ([id_sketch_particular])  REFERENCES [sketch_particular]([id])
);
GO


CREATE NONCLUSTERED INDEX [FK_60] ON [sketchs_particulares_x_capitulos] 
 (
  [id_capitulo] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_73] ON [sketchs_particulares_x_capitulos] 
 (
  [id_sketch_particular] ASC
 )

GO

-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [sketches_particulares_x_actores]
CREATE TABLE [sketches_particulares_x_actores]
(
 [id_1]                 int NOT NULL ,
 [id_sketch_particular] int NOT NULL ,
 [id_actor]             int NOT NULL ,


 CONSTRAINT [PK_91] PRIMARY KEY CLUSTERED ([id_1] ASC),
 CONSTRAINT [FK_107] FOREIGN KEY ([id_actor])  REFERENCES [actores]([id]),
 CONSTRAINT [FK_87] FOREIGN KEY ([id_sketch_particular])  REFERENCES [sketch_particular]([id])
);
GO


CREATE NONCLUSTERED INDEX [FK_109] ON [sketches_particulares_x_actores] 
 (
  [id_actor] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_89] ON [sketches_particulares_x_actores] 
 (
  [id_sketch_particular] ASC
 )

GO

-- ********************** SqlDBM: Microsoft SQL Server **********************
-- * Generated by SqlDBM: chachacha_db, v10 by cesarhernanruscica@gmail.com *
-- ************************************** [actores_x_personajes]
CREATE TABLE [actores_x_personajes]
(
 [id]           int NOT NULL ,
 [id_actor]     int NOT NULL ,
 [id_personaje] int NOT NULL ,


 CONSTRAINT [PK_118] PRIMARY KEY CLUSTERED ([id] ASC),
 CONSTRAINT [FK_119] FOREIGN KEY ([id_actor])  REFERENCES [actores]([id]),
 CONSTRAINT [FK_150] FOREIGN KEY ([id_personaje])  REFERENCES [personajes]([id])
);
GO


CREATE NONCLUSTERED INDEX [FK_121] ON [actores_x_personajes] 
 (
  [id_actor] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_152] ON [actores_x_personajes] 
 (
  [id_personaje] ASC
 )

GO